image: node:20-alpine

stages:
  - release

cache:
  - key:
      files:
        - "package-lock.json"
    paths:
      - node_modules/
    policy: pull-push

variables:
  GITLAB_AUTH_TOKEN: $CI_PUSH_TOKEN
  GIT_COMMITTER_EMAIL: $GIT_AUTHOR_EMAIL
  GIT_COMMITTER_NAME: $GIT_AUTHOR_NAME
  NPM_TOKEN: $GITLAB_TOKEN

release:
  stage: release
  before_script:
    - apk add --no-cache bash git
    - |
      if [ ! -d "node_modules" ]; then
        echo "Cache restoration failed. Recreating cache..."
        rm -rf node_modules/
        npm ci
      fi
  script:
    - npm ci
    - npm run build
    - npx semantic-release
